-- STAGING ONLY: reverse-engineered from production catalog metadata.
-- Apply only to cws-staging, never to production. No production rows are copied.

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text,
  revenue_split_pct integer default 50,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.fleets (
  id bigint generated by default as identity primary key,
  partner_id bigint not null references public.partners(id),
  name text not null,
  location text,
  max_workers integer not null default 0,
  allowed_start_hour integer,
  allowed_end_hour integer,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  hourly_rate numeric
);

create table if not exists public.jobs (
  id text primary key,
  blend_link text not null,
  blend_file text not null,
  status text not null default 'queued' check (status in ('queued','active','completed','failed','canceled')),
  created_at timestamptz not null default now(),
  max_failed_tasks_threshold numeric default 0.05,
  failed_tasks_count integer not null default 0,
  total_frames integer,
  seconds_per_frame numeric,
  chunking_status text default 'pending' check (chunking_status in ('pending','probing','chunked')),
  fps numeric default 24,
  priority integer default 10,
  merge_lock_at timestamptz
);

create table if not exists public.tasks (
  id bigint generated always as identity primary key,
  job_id text not null references public.jobs(id),
  frame_start integer not null,
  frame_end integer not null,
  status text not null default 'queued' check (status in ('queued','active','done','soft_failed','failed')),
  worker_id text,
  claimed_at timestamptz,
  last_heartbeat timestamptz,
  retry_count integer not null default 0,
  failed_by text[] default '{}',
  generation integer not null default 1,
  error_category text check (error_category in ('transient','persistent','permanent')),
  min_vram_mb integer,
  last_log text,
  log_updated_at timestamptz,
  current_stage text,
  stage_entered_at timestamptz
);

create table if not exists public.workers (
  worker_id text primary key,
  fleet_id bigint not null references public.fleets(id),
  gpu_name text,
  vram_mb integer,
  status text not null default 'idle' check (status in ('idle','busy','offline')),
  last_seen_at timestamptz not null default now(),
  registered_at timestamptz not null default now(),
  crash_count integer not null default 0,
  last_crash_at timestamptz,
  last_crash_message text,
  desired_state text,
  observed_state text,
  health_state text,
  current_task_id bigint references public.tasks(id),
  current_generation integer,
  boot_id text,
  session_id text,
  agent_version text,
  worker_version text,
  last_transition_at timestamptz,
  state_reason text
);

alter table public.tasks add constraint tasks_worker_id_fkey
  foreign key (worker_id) references public.workers(worker_id) not valid;

create index if not exists idx_tasks_job_status on public.tasks(job_id,status,frame_start);
create index if not exists idx_workers_fleet_status on public.workers(fleet_id,status);
create index if not exists idx_workers_current_task_id on public.workers(current_task_id);

alter table public.fleets enable row level security;
alter table public.workers enable row level security;
alter table public.jobs enable row level security;
alter table public.tasks enable row level security;

create policy "allow read fleets" on public.fleets for select to public using (true);
create policy "allow read workers" on public.workers for select to public using (true);
create policy "allow read jobs" on public.jobs for select to public using (true);
create policy "allow read tasks" on public.tasks for select to public using (true);

create or replace function public.register_worker(p_worker_id text, p_fleet_id bigint, p_gpu_name text default null, p_vram_mb integer default null) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  insert into workers(worker_id,fleet_id,gpu_name,vram_mb,status,last_seen_at)
  values(p_worker_id,p_fleet_id,p_gpu_name,p_vram_mb,'idle',now())
  on conflict(worker_id) do update set fleet_id=excluded.fleet_id,gpu_name=excluded.gpu_name,vram_mb=excluded.vram_mb,status='idle',last_seen_at=now();
end; $$;

create or replace function public.worker_ping(p_worker_id text) returns void
language plpgsql security definer set search_path = public, pg_temp as $$
begin update workers set last_seen_at=now(),status=case when status='offline' then 'idle' else status end where worker_id=p_worker_id; end; $$;

create or replace function public.report_heartbeat(p_task_id bigint,p_generation integer,p_worker_id text) returns boolean
language plpgsql security definer set search_path = public, pg_temp as $$
declare n integer; begin update tasks set last_heartbeat=now() where id=p_task_id and generation=p_generation and worker_id=p_worker_id and status='active'; get diagnostics n=row_count; return n>0; end; $$;

create or replace function public.claim_task(p_job_id text,p_worker_id text) returns table(task_id bigint,out_frame_start integer,out_frame_end integer,out_generation integer)
language plpgsql set search_path = public, pg_temp as $$
begin return query update tasks set status='active',worker_id=p_worker_id,claimed_at=now(),last_heartbeat=now() where id=(select t.id from tasks t where t.job_id=p_job_id and t.status='queued' order by t.frame_start limit 1 for update skip locked) returning tasks.id,tasks.frame_start,tasks.frame_end,tasks.generation; end; $$;

create or replace function public.claim_task(p_job_id text,p_worker_id text,p_worker_vram_mb integer default null) returns table(task_id bigint,out_frame_start integer,out_frame_end integer,out_generation integer)
language plpgsql security definer set search_path = public, pg_temp as $$
begin return query update tasks set status='active',worker_id=p_worker_id,claimed_at=now(),last_heartbeat=now() where id=(select t.id from tasks t where t.job_id=p_job_id and t.status='queued' and (t.min_vram_mb is null or (p_worker_vram_mb is not null and t.min_vram_mb<=p_worker_vram_mb)) order by t.frame_start limit 1 for update skip locked) returning tasks.id,tasks.frame_start,tasks.frame_end,tasks.generation; end; $$;

create or replace function public.claim_next_task(p_worker_id text,p_worker_vram_mb integer default 0) returns table(out_task_id bigint,out_job_id text,out_frame_start integer,out_frame_end integer,out_generation integer)
language plpgsql set search_path = public, pg_temp as $$
begin return query update tasks set status='active',worker_id=p_worker_id,claimed_at=now(),last_heartbeat=now() where id=(select t.id from tasks t left join jobs j on j.id=t.job_id where t.status='queued' and (p_worker_vram_mb=0 or t.min_vram_mb is null or t.min_vram_mb<=p_worker_vram_mb) order by coalesce(j.priority,999),t.frame_start limit 1 for update skip locked) returning tasks.id,tasks.job_id,tasks.frame_start,tasks.frame_end,tasks.generation; end; $$;

create or replace function public.complete_task(p_task_id bigint,p_generation integer,p_worker_id text) returns boolean
language plpgsql security definer set search_path = public, pg_temp as $$
declare n integer; begin update tasks set status='done' where id=p_task_id and generation=p_generation and worker_id=p_worker_id and status='active'; get diagnostics n=row_count; if n>0 then update workers set status='idle',last_seen_at=now() where worker_id=p_worker_id; end if; return n>0; end; $$;

create or replace function public.fail_task(p_task_id bigint,p_generation integer,p_worker_id text,p_error_type text) returns text
language plpgsql security definer set search_path = public, pg_temp as $$
declare j text; begin select job_id into j from tasks where id=p_task_id and generation=p_generation and worker_id=p_worker_id and status='active'; if j is null then return 'rejected'; end if; if p_error_type='transient' then update tasks set status='queued',worker_id=null,claimed_at=null,last_heartbeat=null,generation=generation+1 where id=p_task_id; else update tasks set status='failed',error_category=case when p_error_type in ('persistent','permanent') then p_error_type else 'permanent' end,worker_id=null where id=p_task_id; end if; update workers set status='idle',last_seen_at=now() where worker_id=p_worker_id; return case when p_error_type='transient' then 'requeued' else 'permanent' end; end; $$;

create or replace function public.update_task_stage(p_task_id bigint,p_generation integer,p_worker_id text,p_stage text,p_frame_num integer default null) returns boolean
language plpgsql security definer set search_path = public, pg_temp as $$
begin update tasks set current_stage=p_stage,stage_entered_at=now(),last_heartbeat=now() where id=p_task_id and generation=p_generation and worker_id=p_worker_id and status='active'; return found; end; $$;

create or replace function public.log_task_event(p_task_id bigint,p_worker_id text,p_message text) returns boolean
language plpgsql security definer set search_path = public, pg_temp as $$
begin update tasks set last_log=left(p_message,500),log_updated_at=now() where id=p_task_id and worker_id=p_worker_id; return found; end; $$;

revoke all on function public.register_worker(text,bigint,text,integer) from public;
revoke all on function public.worker_ping(text) from public;
revoke all on function public.report_heartbeat(bigint,integer,text) from public;
revoke all on function public.claim_task(text,text) from public;
revoke all on function public.claim_task(text,text,integer) from public;
revoke all on function public.claim_next_task(text,integer) from public;
revoke all on function public.complete_task(bigint,integer,text) from public;
revoke all on function public.fail_task(bigint,integer,text,text) from public;
revoke all on function public.update_task_stage(bigint,integer,text,text,integer) from public;
revoke all on function public.log_task_event(bigint,text,text) from public;
grant execute on all functions in schema public to anon, authenticated;
