export const RESUMABLE_CHUNK_SIZE_BYTES = 8 * 1024 * 1024;
export const RESUMABLE_MAX_FILE_SIZE_BYTES = 2 * 1024 * 1024 * 1024;
export const RESUMABLE_MAX_PARTS = Math.ceil(RESUMABLE_MAX_FILE_SIZE_BYTES / RESUMABLE_CHUNK_SIZE_BYTES);
